### ISSUE TITLE
it does not work for the new update

### ISSUE THREAD

**Issue by myStitch14** [Loafiat/Newtilla#2]
please fix it for the new update

**Comment by Loafiat** [comment]
It does work in the new update. What issue in particular are you having.

**Comment by myStitch14** [comment]
well when i put the dll into my plugins folder and launch the game it has the modded buttons but they dont have arrows and they dont do anything when i click it

**Comment by myStitch14** [comment]
i dont know what that means

**Comment by Loafiat** [comment]
open that and where it says HideManagerGameObject = false
change it to
HideManagerGameObject = true

**Comment by myStitch14** [comment]
what do i open? im just installing the dll. im not like rebuilding it or anything

**Comment by myStitch14** [comment]
wait so do you want me to download the source files, enter the code, then change it and build it?

**Comment by Loafiat** [comment]
no

**Comment by Loafiat** [comment]
in your gorilla tag game files

**Comment by myStitch14** [comment]
where is it in my files?

**Comment by myStitch14** [comment]
sorry if this is taking a long time :/

**Comment by Loafiat** [comment]
are you using steam?

**Comment by myStitch14** [comment]
no i use the meta quest link app

**Comment by Loafiat** [comment]
go to this folder: C:\Program Files\Oculus\Software\Software\another-axiom-gorilla-tag\BepInEx\config\BepInEx.cfg

**Comment by Loafiat** [comment]
it should open a file

**Comment by myStitch14** [comment]
do i open it with windows visual studios?

**Comment by Loafiat** [comment]
that works

**Comment by Loafiat** [comment]
and find HideManagerGameObject in there

**Comment by myStitch14** [comment]
so i just set it to true then it works?

**Comment by Loafiat** [comment]
yes (sorry for late reply)

**Comment by myStitch14** [comment]
thanks it works!
